version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    networks:
      - flink-demo
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.13/data  
      - zookeeper-conf:/opt/zookeeper-3.4.13/conf
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    networks:
      - flink-demo
    ports:
      - 9092:9092
    volumes:
      - kafka:/kafka
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: ${hostname}
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1" # create topic test
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  
  go-collect:
    image: go-collect:latest
    networks: 
      flink-demo:
    depends_on:
      - kafka
  
  jobmanager:
    image: flink:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./test:/test
    networks:
      - flink-demo

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./test-data:/test-data
    networks:
      - flink-demo
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  
networks:
  flink-demo:

volumes:
  kafka: 
  zookeeper-data:
  zookeeper-conf:




















  # jobmanager:
  #   image: flink
  #   expose:
  #     - "6123"
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager
 
  # taskmanager:
  #   image: flink
  #   expose:
  #     - "6121"
  #     - "6122"
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager