version: "3"
services:
  standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650 
    ports:
      - 6650:6650
    # environment:
    #   - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - pulsar-data:/pulsar/data
    command: bin/pulsar standalone
    networks:
      - flink-demo
  
  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://standalone:8080
    networks:
      - flink-demo
  
  data:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: data-generate:v0.2.0
    networks:
      - flink-demo
    volumes:
      - ./data-generate:/data
    depends_on:
      - standalone

  jobmanager:
    image: flink:1.9.1-scala_2.11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    # volumes:
    #   - ./test:/test
    networks:
      - flink-demo

  taskmanager:
    image: flink:1.9.1-scala_2.11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    # volumes:
    #   - ./test-data:/test-data
    networks:
      - flink-demo
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  
networks:
  flink-demo:

volumes:
  pulsar-data: 





















  # jobmanager:
  #   image: flink
  #   expose:
  #     - "6123"
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager
 
  # taskmanager:
  #   image: flink
  #   expose:
  #     - "6121"
  #     - "6122"
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager